services:
  db:
    image: postgres:15
    container_name: notes-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./back-end
    container_name: notes-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data: